/*
 * Copyright 2025, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Test runner for VS Code extension integration tests
 * This file launches VS Code with the extension loaded for integration testing
 */

import * as path from 'path';
import * as cp from 'child_process';
import * as fs from 'fs';
import { runTests, downloadAndUnzipVSCode, resolveCliArgsFromVSCodeExecutablePath } from '@vscode/test-electron';

async function main(): Promise<void> {
  try {
    // The folder containing the Extension Manifest package.json
    // __dirname is test/integration/out, so we need to go up 3 levels to reach project root
    const extensionDevelopmentPath = path.resolve(__dirname, '../../../');
    
    // Verify the path is correct
    console.log(`Extension development path: ${extensionDevelopmentPath}`);
    const fs = require('fs');
    if (!fs.existsSync(path.join(extensionDevelopmentPath, 'package.json'))) {
      throw new Error(`package.json not found at ${extensionDevelopmentPath}. Check extensionDevelopmentPath.`);
    }
    
    // The path to the test runner script
    const extensionTestsPath = path.resolve(__dirname, './suite/index');
    
    // Extension dependencies that need to be installed
    const extensionDependencies = [
      'salesforce.salesforcedx-vscode-core',
      'salesforce.salesforcedx-vscode-apex-replay-debugger',
      'salesforce.agent-script-language-client'
    ];

    console.log('Downloading VS Code...');
    
    // Download VS Code
    const vscodeExecutablePath = await downloadAndUnzipVSCode('stable');
    
    console.log('Installing extension dependencies...');
    
    // Resolve CLI arguments for the downloaded VS Code
    const [cliPath, ...args] = resolveCliArgsFromVSCodeExecutablePath(vscodeExecutablePath);
    
    // Install required extension dependencies
    for (const extensionId of extensionDependencies) {
      console.log(`Installing ${extensionId}...`);
      const result = cp.spawnSync(cliPath, [...args, '--install-extension', extensionId], {
        encoding: 'utf-8',
        stdio: 'inherit'
      });
      
      if (result.error) {
        console.warn(`Warning: Failed to install ${extensionId}:`, result.error.message);
        // Continue anyway - the extension might already be installed or might not be critical
      } else if (result.status !== 0) {
        console.warn(`Warning: Installation of ${extensionId} returned non-zero exit code: ${result.status}`);
        // Continue anyway - the extension might already be installed
      } else {
        console.log(`Successfully installed ${extensionId}`);
      }
    }

    console.log('Running integration tests...');
    
    // Run the integration tests with the downloaded VS Code
    // This will run ALL .nut.js files found in the suite directory
    try {
      await runTests({
        vscodeExecutablePath,
        extensionDevelopmentPath,
        extensionTestsPath,
        launchArgs: [
          // Open a test workspace (this should trigger activation via workspaceContains:sfdx-project.json)
          // Use source fixtures directory (not the compiled out directory)
          path.resolve(__dirname, '../fixtures/test-workspace'),
          // Disable other extensions that might interfere
          '--disable-extension=ms-vscode.vscode-typescript-next',
          // Disable VS Code telemetry
          '--disable-telemetry'
        ],
        // Give extension time to activate and disable telemetry
        extensionTestsEnv: {
          // Disable telemetry via environment variables
          VSCODE_DISABLE_CRASH_REPORTER: '1',
          // Disable Salesforce telemetry
          ...process.env
        }
      });
    } finally {
      // Clean up the out directory AFTER all NUT tests have completed
      // This runs once after the entire test suite finishes, not after individual tests
      // The out directory will be regenerated by compile:integration on the next test run
      console.log('All tests completed. Cleaning up test artifacts...');
      try {
        const outDir = path.resolve(__dirname);
        if (fs.existsSync(outDir)) {
          // Remove the entire out directory - it's regenerated by compile:integration
          fs.rmSync(outDir, { recursive: true, force: true });
          console.log('Removed test/integration/out directory');
        }
        console.log('Cleanup complete');
      } catch (cleanupError: any) {
        console.warn(`Warning: Failed to clean up test artifacts: ${cleanupError.message}`);
        // Don't fail the test run if cleanup fails
      }
    }
  } catch (err) {
    console.error('Failed to run tests:', err);
    process.exit(1);
  }
}

main();

