#name: Einstein for Developers End to End Tests
#
#on:
#  workflow_dispatch:
#    inputs:
#      automationBranch:
#        description: 'Set the branch to use for automation tests'
#        required: false
#        default: 'main'
#        type: string
#      testSidebar:
#        description: 'Test Einstein Sidebar'
#        required: false
#        default: true
#        type: boolean
#      testBCG:
#        description: 'Test BCG'
#        required: false
#        default: true
#        type: boolean
#      testAutoCompleteSetting:
#        description: 'Test Autocomplete Setting'
#        required: false
#        default: true
#        type: boolean
#      testTestsGeneration:
#        description: 'Test Tests Generation'
#        required: false
#        default: true
#        type: boolean
#      vscodeVersion:
#        description: 'VSCode Version'
#        required: false
#        default: 'stable'
#        type: string
#      runId:
#        description: 'Run ID of the workflow run that created the vsixes'
#        required: true
#        type: string
#
#  workflow_call:
#    inputs:
#      automationBranch:
#        description: 'Set the branch to use for automation tests'
#        required: false
#        default: 'main'
#        type: string
#      testSidebar:
#        description: 'Test Einstein Sidebar'
#        required: false
#        default: true
#        type: boolean
#      testBCG:
#        description: 'Test BCG'
#        required: false
#        default: true
#        type: boolean
#      testAutoCompleteSetting:
#        description: 'Test Autocomplete Setting'
#        required: false
#        default: true
#        type: boolean
#      testTestsGeneration:
#        description: 'Test Tests Generation'
#        required: false
#        default: true
#        type: boolean
#      vscodeVersion:
#        description: 'VSCode Version'
#        required: false
#        default: 'stable'
#        type: string
#      runId:
#        description: 'Run ID of the workflow run that created the vsixes'
#        required: true
#        type: string
#
#jobs:
#  testSidebar:
#    if: ${{ inputs.testSidebar }}
#    uses: ./.github/workflows/runE2ETest.yml
#    secrets: inherit
#    with:
#      automationBranch: ${{ inputs.automationBranch }}
#      testToRun: 'testSidebar.e2e.ts'
#      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
#      runId: ${{ inputs.runId }}
#
#  testBCG:
#    if: ${{ inputs.testBCG }}
#    uses: ./.github/workflows/runE2ETest.yml
#    secrets: inherit
#    with:
#      automationBranch: ${{ inputs.automationBranch }}
#      testToRun: 'testBCG.e2e.ts'
#      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
#      runId: ${{ inputs.runId }}
#
#  testAutoCompleteSetting:
#    if: ${{ inputs.testAutoCompleteSetting }}
#    uses: ./.github/workflows/runE2ETest.yml
#    secrets: inherit
#    with:
#      automationBranch: ${{ inputs.automationBranch }}
#      testToRun: 'testAutoCompleteSetting.e2e.ts'
#      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
#      runId: ${{ inputs.runId }}
#
#  testTestsGeneration:
#    if: ${{ inputs.testTestsGeneration }}
#    uses: ./.github/workflows/runE2ETest.yml
#    secrets: inherit
#    with:
#      automationBranch: ${{ inputs.automationBranch }}
#      testToRun: 'testTestsGeneration.e2e.ts'
#      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
#      runId: ${{ inputs.runId }}
#
#  slack_success_notification:
#    if: ${{ success() }}
#    needs: [testSidebar, testBCG, testAutoCompleteSetting, testTestsGeneration]
#    uses: ./.github/workflows/slackNotification.yml
#    secrets: inherit
#    with:
#      title: 'Einstein for Developers End to End Tests'
#      vscodeVersion: ${{ inputs.vscodeVersion }}
#      testsBranch: ${{ inputs.automationBranch }}
#      summary: '\n- test sidebar: ${{ needs.testSidebar.result }}\n- test BCG: ${{ needs.testBCG.result }}\n- test autocomplete setting: ${{ needs.testAutoCompleteSetting.result }}\n- test tests generation: ${{ needs.testTestsGeneration.result }}\n'
#      result: 'All the tests passed.'
#      workflow: 'actions/runs/${{ github.run_id }}'
#      type: 'e2e'
#
#  slack_failure_notification:
#    if: ${{ failure() }}
#    needs: [testSidebar, testBCG, testAutoCompleteSetting, testTestsGeneration]
#    uses: ./.github/workflows/slackNotification.yml
#    secrets: inherit
#    with:
#      title: 'Einstein for Developers End to End Tests'
#      vscodeVersion: ${{ inputs.vscodeVersion }}
#      testsBranch: ${{ inputs.automationBranch }}
#      summary: '\n- test sidebar: ${{ needs.testSidebar.result }}\n- test BCG: ${{ needs.testBCG.result }}\n- test autocomplete setting: ${{ needs.testAutoCompleteSetting.result }}\n- test tests generation: ${{ needs.testTestsGeneration.result }}\n'
#      result: 'Not all the tests passed.'
#      workflow: 'actions/runs/${{ github.run_id }}'
#      type: 'e2e'
#
#  slack_cancelled_notification:
#    if: ${{ cancelled() }}
#    needs: [testSidebar, testBCG, testAutoCompleteSetting, testTestsGeneration]
#    uses: ./.github/workflows/slackNotification.yml
#    secrets: inherit
#    with:
#      title: 'Einstein for Developers End to End Tests'
#      vscodeVersion: ${{ inputs.vscodeVersion }}
#      testsBranch: ${{ inputs.automationBranch }}
#      summary: '\n- test sidebar: ${{ needs.testSidebar.result }}\n- test BCG: ${{ needs.testBCG.result }}\n- test autocomplete setting: ${{ needs.testAutoCompleteSetting.result }}\n- test tests generation: ${{ needs.testTestsGeneration.result }}\n'
#      result: 'The workflow was cancelled.'
#      workflow: 'actions/runs/${{ github.run_id }}'
#      type: 'e2e'
