name: End to End Tests
on:
  workflow_run:
    workflows:
      - Nightly Build Main
      - Test, Build, and Release
    types:
      - completed

  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'main'
        type: string
      afdxE2ETests:
        description: 'AFDX E2E tests'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: 'stable'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string
jobs:
  AFDX_E2E_tests:
    if: ${{ inputs.afdxE2ETests || github.event_name == 'workflow_run' }}
    uses: ./.github/workflows/afdxE2E.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'main' }}
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id }}
