name: Unit Tests Windows
on:
  workflow_call:
    inputs:
      branch-name:
        description: Branch name to run this workflow on
        required: false
        default: ${{ github.ref_name }}
        type: string

jobs:
  windows-unit-tests:
    strategy:
      matrix:
        node_version: [lts/-1, lts/*]
      fail-fast: false
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Configure Git for private repo access
        run: git config --global --add url."https://${{ secrets.IDEE_GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: yarn install --frozen-lockfile
      - run: yarn run compile
      - run: yarn run test
