name: Unit Tests

on:
  workflow_call:
    inputs:
      branch-name:
        description: Branch name to run this workflow on
        required: false
        default: ${{ github.ref_name }}
        type: string
jobs:
  linux-unit-tests:
    uses: ./.github/workflows/unitTestsLinux.yml
    secrets: inherit
    with:
      branch-name: ${{ inputs.branch-name }}
  windows-unit-tests:
    uses: ./.github/workflows/unitTestsWindows.yml
    secrets: inherit
    with:
      branch-name: ${{ inputs.branch-name }}
