#name: Update Public Repository with New Release
#run-name: ${{ github.triggering_actor }} is updating our public repo from ${{ github.ref_name }}
#on:
#  workflow_dispatch: #  Button for publishing from input branch in case there is a failure on the release.
#
#jobs:
#  publish-start-notification:
#    name: 'Publish EGPT Extension to Pilot Repository'
#    uses: ./.github/workflows/slackNotification.yml
#    secrets: inherit
#    with:
#      title: 'Publish in EGPT Extension to Pilot Repository waiting for approval in github.'
#      notification: 'New Release triggered publish job is ready for approval.'
#      type: 'notification'
#      workflow: 'pilotRelease.yml'
#  get-release-version:
#    uses: ./.github/workflows/getReleaseVersion.yml
#    secrets: inherit
#    with:
#      branch-name: ${{ github.ref_name }}
#  githubRelease:
#    environment: publish
#    needs: [publish-start-notification, get-release-version]
#    runs-on: ubuntu-latest
#    env:
#      PUBLISH_VERSION: ${{ needs.get-release-version.outputs.release-version }}
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          ref: ${{ github.ref_name }}
#          token: ${{ secrets.IDEE_GH_TOKEN }}
#      - name: Create new release in the forcedotcom/Einstein-GPT-for-Developers repository
#        run: |
#          mkdir ./releases
#          gh release download -D ./releases v${{ env.PUBLISH_VERSION }} -p "*.vsix"
#          ls -l ./releases
#          gh release create "v${{ env.PUBLISH_VERSION }}" ./releases/*.vsix --title "Release v${{ env.PUBLISH_VERSION }}" --notes-file "CHANGELOG.md" -R forcedotcom/Einstein-GPT-for-Developers
#        env:
#          GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
